[platformio]
description = Smart_Posture_Corrector

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -Ilib/Pins
    -Ilib/Sensors/mpu6050_sensor
    -Ilib/Power/battery_level
    -Ilib/Display/led_indicator
    -Ilib/Actuators/buzzer
    -Ilib/Actuators/vibration_motor
    -Ilib/Input/button
    -Ilib/Storage/sd_card
    -Ilib/Control/posture_logic
    -Ilib/System/reset
    -Ilib/System/error_handling
    -Ilib/System/sleep_wake
