[platformio]
description=Solar_Powered Egg_Incubator

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.36.5
    adafruit/Adafruit AHTX0@^2.0.5
    adafruit/RTClib@^2.1.4
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_ENABLE_PERIPHERAL_MANAGER=1
