[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_ENABLE_PERIPHERAL_MANAGER=1
lib_deps =
    olikraus/U8g2@^2.36.17
