[platformio]
description = NFC_Card_Payment_System

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
lib_deps =
    adafruit/Adafruit NeoPixel
    olikraus/U8g2
    adafruit/RTClib
    adafruit/Adafruit PN532
