[platformio]
description = Solar_Powered_Irrigation_System

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_ENABLE_PERIPHERAL_MANAGER=1

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    olikraus/U8g2@^2.35.19
