[platformio]
description = Smart_Robotic_Car_With_PID_control

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    madhephaestus/ESP32Servo@^3.0.6

build_flags =
    -DARDUINO_ENABLE_PERIPHERAL_MANAGER=1
